releaseType: java-bom
handleGHRelease: true
manifest: true
primaryBranch: main
branches:
    - branch: java7
      releaseType: java-yoshi
      bumpMinorPreMajor: true
    - branch: 26.1.x
      releaseType: java-backport
    - branch: protobuf-4.x-rc
      releaseType: java-yoshi
