releaseType: java-bom
handleGHRelease: true
manifest: true
primaryBranch: main
branches:
    - releaseType: java-yoshi
      bumpMinorPreMajor: true
      branch: java7
    - releaseType: java-backport
      branch: 26.1.x
