releaseType: java-bom
handleGHRelease: true
primaryBranch: main
versioning: "always-bump-minor"
branches:
  - releaseType: java-yoshi
    handleGHRelease: true
    bumpMinorPreMajor: true
    branch: java7
  - releaseType: java-backport
    manifest: true
    handleGHRelease: true
    branch: 26.1.x
