on:
  pull_request:
    paths:
      - 'release-note-generation/**'
name: release-note-generation-test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: maven
    - run: java -version
    - name: Run test in release-note-generation
      shell: bash
      run: |
        mvn -B -ntp verify
      working-directory: release-note-generation
      env:
        GH_TOKEN: ${{ github.token }}

  dry-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: maven
    - run: java -version
    - name: Dry-run release-note-generation
      shell: bash
      run: |
        mvn -B -ntp compile
        # This generates release_note.md file
        mvn -B -ntp exec:java \
            -Dlibraries-bom.version="26.2.0" \
            -Dgoogle-cloud-java.version="1.1.0"
      working-directory: release-note-generation
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Show generated release note
      shell: bash
      run: |
        # This fails if the file does not exist
        cat release_note.md
      working-directory: release-note-generation
