'on':
  push:
    branches:
      - 26.75.x
  pull_request: null
name: test for tests/validate-bom logic
jobs:
  test-invalid-bom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch the bad protobuf-bom version 3.22.1
        shell: bash
        run: >
          mkdir -p bad-protobuf-bom

          curl
          https://repo1.maven.org/maven2/com/google/protobuf/protobuf-bom/3.22.1/protobuf-bom-3.22.1.pom
          \
              --output bad-protobuf-bom/pom.xml
      - name: Check the bad BOM
        uses: ./tests/validate-bom
        id: validate-bom
        with:
          bom-path: bad-protobuf-bom/pom.xml
        continue-on-error: true
      - name: Ensure the validate-bom invalidated the bad BOM
        shell: bash
        if: steps.validate-bom.outcome != 'failure'
        run: |
          echo "The validate-bom check should have invalidated the bad BOM"
          exit 1
