name: Generate Javadocs for google-cloud-java
# Run this workflow once the Javadoc generation for handwritten modules has run
on:
  workflow_run:
    workflows: [ "Generate Javadocs for handwritten libraries" ]
    types:
    - completed
    workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: maven

    - name: Save checkout tags for google-cloud-java
      id: save-tags
      run: |
        GOOGLE_CLOUD_JAVA="gapic-libraries-bom"
        VARIABLES_FILE="site/data/javaModulesVersions.yaml"

        GOOGLE_CLOUD_JAVA_TAG=$(grep -oP "(?<=${GOOGLE_CLOUD_JAVA}: \")[^\"]*" "$VARIABLES_FILE" | tr -d '\n')
        echo "GOOGLE_CLOUD_JAVA_TAG=$GOOGLE_CLOUD_JAVA_TAG" >> $GITHUB_ENV

    - name: Generate javadocs for modules within google-cloud-java repo
      run: |
        git clone https://github.com/googleapis/google-cloud-java.git
        git -C google-cloud-java checkout ${{ env.GOOGLE_CLOUD_JAVA_TAG }}
        while read -r artifact directory
        do
          echo "ARTIFACT=$artifact"
          echo "DIRECTORY=$directory"
          echo "Creating and clearing directory for javadocs for ${artifact}"
          mkdir -p site/static/${artifact} # Make sure the output directory exists
          rm -rf site/static/${artifact}/ # Clear any existing files in the output directory
          echo "Generating javadocs for ${artifact}"
          mvn -f ${directory}/pom.xml javadoc:aggregate -Dmaven.javadoc.failOnError=false && mv ${directory}/target/site/apidocs/ site/static/${artifact}/
        done < site/javadocHelpers/google-cloud-java_javadocs_modules.txt

    - name: Commit Javadocs
      run: |
        git -C site/static/ add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add Javadocs for google-cloud-java modules" -a || echo "No changes to commit"
        git pull --rebase origin main
        git push
      env:
        GH_TOKEN: ${{ github.token }}