name: Update README with libraries-bom table
# Run this workflow upon published release

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install pyyaml

    - name: Update table of artifacts
      run: |
        echo "Updating README.md with table of artifacts associated with the latest libraries-bom..."
        python libraries-bom-table-generation/updateREADMETable.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README with release table"
        git checkout -b update-readme
        git push origin update-readme

    - name: Create Pull Request
      run: |
        gh pr create --base main --head update-readme --title "Update README with release table" --body "Updating README with the table of artifacts associated with the latest libraries-bom release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
